### ISSUE TITLE
[eFEAT] Lineup tab: better use of space to improve visibility

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#133]
Option 1 ) The idea would be to have different width for the player box for player on the field and player set as substitutes. Player box on the field would be wider to expend as much as the substitutes lines, it would allow to have better name visibility. =>  It might be tricky to be done.

Option 2) Another possibility much simpler to implement would be to remove the shirt from the player box. I don't think it brings anything and it would give more space to player name display.
 
@brokenelevator @yaute74 @mistermax80  @DavidatorusF  Let me know what you think

**Comment by brokenelevator** [comment]
@akasolace 
1) The substitutes don't even fit on my screen, so that is a problem but I can live with that. Aside from that I see no problem with option 1.

2) I kind of used to having shirt there but to be honest it seems quite useless. So option 2 seems like a reasonable idea. It won't give much space though. We can remove it along with numbers but those are not completely useless.

**Comment by akasolace** [comment]
#146 can be dealt had the same time

**Comment by akasolace** [comment]
closed by #175 (thank you @yaute74 !!)
