### ISSUE TITLE
[eFEAT] List of players listed in dropdown for Lineup

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#160]
**Is your feature request related to a problem? Please describe.**
I am working on improved formula rating for players. What we will have in HO when this is done is the evaluation of each player per position as a % to perfect fit.

**example:**
player A:  IM  50 %  ,  WI 40 %
player B:  IM   37 %  , WI 38% 
....

Considering this dropdown menu in Lienup should be smarter than simply listing the players by 
 formula ranking. On the example above, we can see that even if player A is a better wing than player B it should still normally be used as an IM.  

Hence I suggest that on top of ranking the player we indicate whether or not the position fits. 
Still on the example above, we could have  on wing dropbox:

  - player A  (greyed or anything indicating that the team might benefit from having him position somewhere else) 
  - player B (black or star or anything indicating he suits the position)

Let me know what you think ?

**Comment by brokenelevator** [comment]
Well, I like the percentage idea. It is nice. What will be the baseline though?

About the other thing I would say no. Who are we to tell who is better fit? So the graying or starring is just...no.
I do get your point but we do not set priorities, managers do. I for one believe that player A is better fit for wing not only because the 2% difference in wing but also higher IM. Sure if I have vacancy in the IM's I'd probably put him to IM but that is me.
Also, what if I have 3 guys with IM > 60? Would you still gray out player A for Winger? The decision is not ours to make.

**Comment by akasolace** [comment]
@brokenelevator I am not saying not to show them, but just to show them in a smarter way than decreasing formula for that position.
There are 2 different information available: who is best for a position and what is the best position for a given player. At the moment only info 1 is used in the dropbox which often display player not in a smart way. 
To be discussed with maybe concrete example.

**Comment by akasolace** [comment]
@brokenelevator  I made some test ranking player by best position fit is also confusing. 

If the user decide to play with let say a Forward TW, he would like HO to indicate the player for that position. But if he hesitate he would like to see what order will contribute most.  It is not possible to achieve both by displaying a single value.

Hence I do not know what to do, indicate both ? 
e.g player A for IM normal would be  6.25 (36%)    6.25 would be the overall contribution, and 36% would be how well he fits for the position. Hence if HO user look how to maximize ratings he would look at first value and if he looks at what player is best for given position/order he would look at second value.

**Comment by brokenelevator** [comment]
@akasolace First of all I don't like the term smart. It is go to term if people want to make choices for you. I usually turn smart features off.
I only see one. 
Best for position is when you have the highest sum of contributions on that position.
Best for a player is when you have the highest sum of contributions on a position.
We have a 'best position' field. It could become a dropdown if someone wants to know best positions in order.
I don't see what is not smart about the way we show players.

I'm not sure what it has to do with anything.  Sure the user can choose FW TW, but also FW DEF. Do you want to display 3 values? What would you sort by?
It lists players with values for the position and order. I don't see what is wrong with that.

As for the percentages, I don't see that. I asked what is the baseline? You say 36%, but what is 100%?
Isn't the best position/order the one that maximize ratings?
Say we have a player on DEF normal. Will his % change if we pick CA?

I'd go for something different. Possibly it already is like that. Player rating for the position is sum of all formation contributions (left/right/center def/mid/att). We could also add a separate value for players contribution to the formation he is now. The first maximize overall rating sum and the second formation contribution. For some good IM is one that gives the most overall and for some one that gives most to MID while sacrificing DEF or ATT.
Not sure what with wingbacks though. They should have both DEF and ATT there. Some people might even want to use them to max out MID. So maybe we should make all the values available. The combined contribution and all the partial (including sides). Preferably with sorting.

**Comment by akasolace** [comment]
>@akasolace First of all I don't like the term smart. It is go to term if people want to make choices for you. I usually turn smart features off. ...

@brokenelevator wow that was a long message. I disagree with you but whatever. HO is an assistant manager it mainly help people do best lineup. At the moment the assistant use absolute performance to place player and this is not optimal. It should use relative performance per position which is what a human would do to maximize overall performance.  Again in my opinion not value are interesting but should be use for different reason. I guess  best will be I ask on HT forum and just do whatever user want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brokenelevator** [comment]
@akasolace I think there is a difference between help (providing data) and help (deciding). I think HO should provide data but I guess if people want HO to take their place I'm also cool with that.

Can you elaborate on the absolute/relative difference you see? because I don't.
Either I'm not human or I have no idea how HO works right now. I think combined(all sectors) and separated(to each sector) contributions of players at a chosen position and order are what is interesting.
Correct me if I'm wrong but in HT it is ratings/values that play, so ratings/values matter.

People's idea of best lineup don't have to match and I think you want to lock them up to one. I still don't understand how are you going to devise this percentage. It has to be relative to a ceiling that is different for all the possibilities.

One thing we do agree on. Ask users and do what they want.

**Comment by akasolace** [comment]
@brokenelevator  it is done as follow, for a given player and position/match order we compute the added rating to each sectors assuming normal coach, normal attitude, nomal TS, confidence, .... and no penalty due to 2nd or 3 player on central position.
Hence for each triplet (player, position, MO) we got 7 ratings contribution.
A single rating is obtained by applying the formula used on HT for ranking best match, i.e :
Total rating = 0.46 * MID rating + 0.32 * ATT rating + 0.22 * DEF rating
for ATT, and DEF, center and side contribute respectively 40% and 30%

The number obtained is the absolute contribution. The one displayed in HO (only scaled by 10 for visibility).

The relative contribution, is simply the absolute contribution / Max Contribution * 10
Max contribution is a player having 20 skills everywhere + max stamina, form  and Technic for defensive forward.
Hence the relative contribution is the percentage of what an ideal player could bring in similar position.

Currently in HO best position for a given player is simply the max of contribution accross all position.
Lineup Assistant, Iterate via player and take highest contribution according to priority set by user. 
For example if user want MID - DEF - ATT,  the asssistant look for best midfield then best WI, ..... this will definitely not guarantee an optimal lineup. Because the algorithm is not good.

Similarly to say that a player best position is the max of absolute contribution is also wrong for me, because of the difference in weight. Even if a player will contribute more a PM maybe he is fundamentally a winger. I mean, imagine an hypothetic player being maxed out everywhere, curently HO would says he is a Midfield because that sector contribute the most, In such a case with relative contribution he would have 100% everywhere meaning he can played everywhere.

**Comment by brokenelevator** [comment]
@akasolace so that is how it works. I like my idea better but I'm hardly an expert.

The relative if through the roof then. The relative contribution would then prefer all 20 player for Forward instead of one also with all 20 but 0 GK. Same could apply to different positions but I'm unsure about DEF contribution in ATT. Shooting contribution in DEF or GK. Sum of team skills is used at times. Like with set pieces.
Also all 20 winger with speed is better than the one without it.  The max is hardly a max.
Negligible maybe?

I will not defend the lineup assistant because I never used it. It is not much better then a dice throw. I would have my IM's in defense. True that the algorithm is not good but define a good one. There are many possibilities. One way of solving those would be to set up rules (guidelines) for each position. Chose from that players, with that skills, specs, contributions. Also maybe priorities for players, ex. DEF then, WI then... I don't know. I may be going too far.

Not for me. I mean unweighted contributions. Like I said those are only information. It is up to manager to place players. If I have a player, a winger, I put him to wing even if he is top of the IM list. He is a winger for a reason. HO is not replacement for MyBrain, even if I'm an idiot.

Isn't it obvious that a player maxed out on every stat can play everywhere? I know it is just an example, but still. For the current weighted values it may be a problem, it is biased. With the unweighted though it would simply say that his overall contribution at MID would be highest but it does not make him a midfielder. Someone might want to max wing, or def and for that purpose he would be better off there. 
Also it does not account for crowding so he may be way more useful at wing than as a 3rd IM. The lineup rating should take that in consideration though. So the manager could test for that.

**Comment by mistermax80** [comment]
@akasolace, the new percentage value it is inserted... So this issue for what scope is open?
What am I missing?

**Comment by akasolace** [comment]
@mistermax80 at the moment player are ranked with absolute value. The idea would also be to indicate the relative value and indicating maybe whether or not it is the best position. Still have to think about how to present it.

**Comment by mistermax80** [comment]
We can think, to leave to user the choice, we can insert a new Param if the user would see the absolute contribute or the player performance (%)

**Comment by mistermax80** [comment]
#282
