### ISSUE TITLE
Lineup doesn't download[BUG]

### ISSUE THREAD

**Issue by l3dz3pp** [akasolace/HO#1788]
**Describe the bug**
Lineup is empty. It's not populated after clicking download.

**Screenshots**
Screenshot attached
![error_1](https://user-images.githubusercontent.com/28995637/216129959-8e473c05-491c-444a-b271-57b11fe59621.jpg)

**Platform information:**
 - OS: [Windows 10 Pro]
 - Version 22H2

Any ideea?

Thank you!

**Comment by wsbrenk** [comment]
fixed by #1784

This is due to a bug in the MatchOrder file of the CHPP API. Error is known to the HTs.
The current HO7 dev version can handle this error by ignoring red card and goal difference criteria of substitutions of your match order.

if you delete your substitution in your current match you should be able to download again.

**Comment by l3dz3pp** [comment]
Solved!

Thank you so much!!
