### ISSUE TITLE
[BUG] Error when deleting the old "other" games

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1821]
When I click on remove all in the database clean-up "other games" and "other friendlies" - it does not delete the games. these are still visible and selectable!

Select "all games" - and then clean up:

![alle Spiele löschen_1](https://user-images.githubusercontent.com/88058929/224548861-14a9f7a2-577d-404b-8629-fba2cb9d759f.jpg)

after clean-up - the games are still there:

![alle Spiele löschen_2](https://user-images.githubusercontent.com/88058929/224548878-d87d6439-2c97-4ad0-9e88-27d1f4c08664.jpg)

and you can still select them:

![alle Spiele löschen_3](https://user-images.githubusercontent.com/88058929/224548891-6fda9b19-176c-4ad5-a945-1d027d2b0a1f.jpg)

Windows 11
HO Beta Vers. 7.0 (r470)

**Comment by masterpatje** [comment]
I think I mentioned this one as well. other matches are other than your own matches as became apparent to me.

Wsbrenk is it like this or was it a bug? And because more users mention this, it might be an idea to redesign this part?

But I would think it through because (regular) friendlies are important to calculate the training correctly. So deleting these should at least be done after a warning message.

I would like options to clean non-essential matches (not linked to training). This as a suggestion.

**Comment by wsbrenk** [comment]
@masterpatje this was a bug that should be fixed now. 

Redesign is part of future releases.
