### ISSUE TITLE
[eFEAT] Activate feedback plugin only if data recently refreshed

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#244]
In order to gather only quality data, we will activate feedback plugin only if data recently refreshed

1) add label "Please make sure your players data are up to date before participating" in the feedback plugin label
2) store somewhere the timestamp at which update has been made (maybe already exist) and add as an additional check before activating "send" button, something like now()-RefreshTimeStamp < 1 h
3) Add corresponding message as trasnlated string i.e if button remains deactivated because of no recent Refresh,. Users need to be informed of what is the issue (similar to other checks)

**Comment by mistermax80** [comment]
Today the server is unavailable... The free hosting service is unavailable...
This situation can be matter with any free hosting, but I reflected on this.
We should decide if the feedback plugin is active or ready to receive data. By json from gitub, we can do this, add other 'request' that HO uses for don't activate the feedback plugin... We can use this for manatainace server or similar situations matter today...
Other this we can insert in gitub json the URL server, this for We take a way to change URL without give an new update.
Let me know what you think.

**Comment by akasolace** [comment]
> By json from gitub, we can do this, add other 'request' that HO uses for don't activate the feedback plugin... We can use this for manatainace server or similar situations matter today...

We can either, do that check beforehand or capture that error in a try/catch and indicate correct message like "Server currently not available, please try later." However, I am not sure what you mean by `by json from github`? 

> Other this we can insert in gitub json the URL server, this for We take a way to change URL without give an new update.

I am also ok with that idea but hopefully this is not something we will need to use anytime soon.

**Comment by mistermax80** [comment]
For json git I mean https://akasolace.github.io/HO/feedback.json
, In this object we can insert if the feedback plugin is active or no, and the specific text for the communication. I think the effect the yesterday issue is an time out of the request... Adobe the users can see as in error don't managed from us.
In this moment th release 2.0 is waiting broken development... So we can try to insert these as options.

**Comment by akasolace** [comment]
> In this object we can insert if the feedback plugin is active or no  

I am not sure I understand,  You want to hardcode in the json whether or not the server is online? Based on what? When/How the json will be updated ?

**Comment by mistermax80** [comment]
I would like insert an information in these object in order to say to HO if the feedbackplugin is active or no.
The update json object will be manual, as when you change for change the request from GK to CD-normal.
In this way, If we know some issue on server or we must put offline the server, we can manage if the users can send data or we can say to user "server is temporary offline, for maintancance activities, you can retry after some hours, or you can read the news on gitub akasolace for updates."
The idea is avoid the user can send data and receive an error and the user can lost the trust on feedback lugin funcionality.

**Comment by akasolace** [comment]
@mistermax80 ok I understand now. Initially, I thought you wanted to do something different. Something like: 
    1. when the user launch feedback panel, HO download json and check server availability (ping) 
    2. if server not available: message is displayed on panel and the send button remains grey 

What do you think of that alternative ?

**Comment by mistermax80** [comment]
No by ping activities, I prefer something manual, in order to we have the total control.
I thought a new field in json object:
1. when the user launch feedback panel, HO download json and check server availability information (new datai in object)
2. if server not available: message is displayed (spcific message retrived by json) on panel and the send button remains grey

**Comment by akasolace** [comment]
@mistermax80  ok for me

**Comment by mistermax80** [comment]
well!

**Comment by akasolace** [comment]
ok I will simply add a line on top like:
"server_status": "up" or  "server_status": "down"
I edit manually the json for now, hence you can start on your side. I will modify the python script later this week.

**Comment by mistermax80** [comment]
ok, the field is ok, but I would like add an other text field, we can used it for show message to users.
In order to explain the reason to server is offline.... (the message will not tralated, or we can write the same sentence in 2 or 3 main languages (english, italian, french, spanish).)
What do you think?

**Comment by akasolace** [comment]
> I would like add an other text field, we can used it for show message to users.
In order to explain the reason to server is offline

For this I would suggest the usual,  we put a message in language files "Server currently not available" And leave it up to user to translate it.

I think a general message is sufficient but if you really want additional message, we can put status_code "0", "1", "2", .... 
with 0= ok,

**Comment by mistermax80** [comment]
My idea is to show an communication, not an simple message.
We could not know which communication to show to users...
We can think a mix status code and free text if we want write an specific communication.

Let me know what do you think... 😄

**Comment by akasolace** [comment]
I personally think it is simpler to stick to simple message like "server down"

**Comment by mistermax80** [comment]
ok!
- Server Down
- Server in Mainatainance
- ????

**Comment by akasolace** [comment]
closed by bbff5b4e452852211065bcc5ff2e74253858ca5a
