### ISSUE TITLE
improve Training estimation (try to replicate exact HT prediction ?)

### ISSUE THREAD

**Issue by Gundor** [akasolace/HO#250]
For somes players the training prediction is wrong about 1 week (add 1 week)

HT training estimation 

(https://i.imgur.com/6GkETqB.jpg)

HO training estimation for same player 

(https://i.imgur.com/IjqvSMs.jpg)

**Platform information:**
 - OS: Windows 
 - Version 10 1903

**HO**
version 1.437

**Comment by akasolace** [comment]
In your example, I see both in HO and HT:
Formidable -> Outstanding in 5 weeks
Outstanding -> Brilliant in 6 weeks

am I missing something?

**Comment by Gundor** [comment]
wrong screeshots, sorry but the bug is still here:

HT: 
https://i.imgur.com/D3aCMkp.jpg

HO:
https://i.imgur.com/ZRVGGhu.jpg

World Class -> Super Natural in 5 Weeks on HT
World Class -> Super Natural in 6 Weeks on HO

Few players are same problem et another are correct prediction

**Comment by akasolace** [comment]
Actually it is:

- World Class -> Super Natural in 10 Weeks on HT
- World Class -> Super Natural in 9 Weeks on HO

but I agree there is still a differnce. I won't call that a bug but I will leave the ticket open for further formula refinements.

**Comment by Gundor** [comment]
an other example, but not so high in training :

HT: https://i.imgur.com/m8ljXkR.jpg
HO: https://i.imgur.com/X2o6Q4u.jpg

**Comment by yaute74** [comment]
As ht-portal has good results, I ask to Schum is formula.
Anybody else speak Russian ? :) [post=17024376.5]

**Comment by yaute74** [comment]
After translate with deepl:
Training.

It is difficult to overestimate the importance of training in CT.
This is the basis of the basics, and moreover, in recent years
it's the teams that make the most of it.
have been coaching since they were 17.

So, let's move on to the training formula:

T = f(lvl) * K(coach) * K(assist) * K(int) * K(stam) * K(train) * K(age) * K(time),
whereabouts
f(lvl) - function of the dependence of the sweatpants' speed on the skill level
K(coach) - Coach level coefficient
K(assist) - sum of the assistant levels coefficient
K(int) - training intensity coefficient
K(stam) - the stamina coefficient in training
K(train) - training type coefficient
K(age) - age coefficient of the player
K(time) - the coefficient of flirtation
and we know from the Rules that T can't be more than 1.0

Before analyzing each component, let me remind you of the coordinate system in the skills: (15895928.2), i.e. 8.0 is the minimum sublevel of the "Excellent" skill.

So,

at lvl<8
f(lvl) = 16.282 * EXP (-0.14 * lvl)

at lvl>=8
f(lvl) = 52.82 / lvl - 1.29

further coefficients:



Coach Koeff
8 1.040
7 1.000
6 0.920
5 0.834
4 0.734


K(assist)


Assists Koeff
10 1.350
9 1.315
8 1.280
7 1.245
6 1.210
5 1.175
4 1.140
3 1.105
2 1.070
1 1.035
0 1.000


K(int)
It's kind of simple here. The intensity of training is the multiplier,
that is, 100% is 1.0.
90% is 0.9

K(stam)
Here we deduct the percentage of the stamen from 1, i.e.
at 5 % of the stadium 1.0 - 5% = 0.95
at 15% of the stadium 1.0 - 15% = 0.85

K(train)
Basic training


Train Koeff
GK 5.10%
Df 2.88%
PM 3.36%
Wg 4.80%
Ps 3.60%.
Sc 3.24%
SP 14.70%.


Other training sessions


Train Koeff
Shoot - Sc 1.50%
Shoot - SP 1.50%
First Pass 3.15%.
Zone Df 1.38%
Wing Att 3.12%


Background training
The ratio of background workout speed to full workout speed is different for different types of workouts:
For Def, Sc, Pass, First Pass and Zone Def, it's 1/6,
for Wing, PM is 1/8, for Wing Att is 5/39.

Correspondingly, the background workout speed coefficients will be as follows:
Df_phone - 0.48%
PM_phone - 0.42%
Wg_phone-- 0.60%.
Ps_phone-- 0.60%.
Sc_phone-- 0.54%.
First Ps_phone - 0.525%
Zone Df_phone - 0.23%
Wing Att_phone - 0.40%

K(age) = 0.9835^(Age-17)

Age - Koeff
17 - 1.000
18 - 0.9835
19 - 0.967
20 - 0.951
21 - 0.936
22 - 0.920
23 - 0.905
24 - 0.890
25 - 0.875
26 - 0.861
27 - 0.847
28 - 0.833
29 - 0.819
30 - 0.806
31 - 0.792
32 - 0.779
33 - 0.766
34 - 0.754
35 - 0.741


K(time)
If a player has played the full slot for 90 minutes, then K(time)=1.0
If the slot is 90 minutes, then K(time)=0.5
if, for example, 36 minutes on the full slot and 90 minutes on the half-slot,
we think, remembering that the total amount of training can not be taken into account more than 90 minutes of flirtation:
K(time)=(1.0*36+(90-36)*0.5)/90=0.7

Translated with www.DeepL.com/Translator

**Comment by akasolace** [comment]
@yaute74  I see 2 ways to improve the formula
      1) we take the one from schumi (nice of him to share it)
      2) we take exact value from HT training prediction tool (bit more work): its not gonna be a formula more an empiric vlookup table

**Comment by yaute74** [comment]
@akasolace how you want to do the 2) ?

**Comment by akasolace** [comment]
@yaute74 either we derive formula (1) or we do interpolation (2) out of HT values

**Comment by yaute74** [comment]
@akasolace  I understand what you say, I just want to know how you want do the interpolation? because there are many parameters that are taken into account.
From my experience the ht-portal formula is quite good

**Comment by akasolace** [comment]
@yaute74 I was really thinking doing something heavy, like collecting all the data ... :-)  
maybe using ht-portal formula is more reasonable  if we are sure it is better than HO current one ...

**Comment by akasolace** [comment]
@wsbrenk could be nice to look at this issue before 5.0 release. Do you want to give it a shot ?

**Comment by wsbrenk** [comment]
@akasolace i could do - but i think we changed something that could have make it better already. we added the handling of skill lost estimation. maybe the values are better today.

**Comment by akasolace** [comment]
to be honest I don't even know where/how those training formula are coded. 
We can also leave this for the future after 5.0 ....

**Comment by wsbrenk** [comment]
@akasolace i will check those formulas and will try to record the differences of their results in comparison to the existing ones in our logs. So we could check which one we want to use for the future. 
don't know if i will get that today (my year number increments again), but at the end of this week we should have it done.

**Comment by akasolace** [comment]
@wsbrenk sure there is no rush and happy birthday :-) !

**Comment by wsbrenk** [comment]
Training | Age | Skill | Full | Partly | Osmosis | current Formula | proposed Formula | difference
-- | -- | -- | -- | -- | -- | -- | -- | --
Torwart | 34 | 15 | 90 | 0 | 0 | 0,112953671 | 0,103553404 | 0,0094
Verteidigung | 23 | 7 | 90 | 0 | 0 | 0,20173751 | 0,192310674 | 0,0094
Verteidigung | 20 | 6 | 90 | 0 | 0 | 0,240192045 | 0,232531357 | 0,0077
Verteidigung | 19 | 5 | 90 | 0 | 0 | 0,283017847 | 0,271962101 | 0,0111
Verteidigung | 18 | 5 | 90 | 0 | 0 | 0,28607491 | 0,27652476 | 0,0096
Verteidigung | 30 | 13 | 90 | 0 | 0 | 0,083883765 | 0,077675972 | 0,0062
Verteidigung | 19 | 4 | 90 | 0 | 0 | 0,341642954 | 0,31283088 | 0,0288
Verteidigung | 31 | 11 | 0 | 0 | 90 | 0,016449758 | 0,016124265 | 0,0003
Verteidigung | 23 | 4 | 0 | 0 | 90 | 0,051344344 | 0,056112168 | -0,0048
Verteidigung | 24 | 5 | 0 | 0 | 90 | 0,041714024 | 0,041708921 | 0,0000
Verteidigung | 29 | 10 | 0 | 0 | 90 | 0,019461571 | 0,018949149 | 0,0005
Verteidigung | 27 | 2 | 0 | 0 | 90 | 0,085014931 | 0,060388707 | 0,0246
Verteidigung | 21 | 3 | 0 | 0 | 90 | 0,067925732 | 0,058010729 | 0,0099
Verteidigung | 32 | 13 | 90 | 0 | 0 | 0,080273888 | 0,075133813 | 0,0051
Verteidigung | 26 | 6 | 0 | 0 | 90 | 0,034375683 | 0,040343882 | -0,0060
Verteidigung | 27 | 5 | 0 | 0 | 90 | 0,039085169 | 0,039678208 | -0,0006
Verteidigung | 22 | 4 | 0 | 0 | 90 | 0,052283349 | 0,049599975 | 0,0027
Verteidigung | 20 | 5 | 0 | 0 | 90 | 0,044699167 | 0,044579121 | 0,0001
Verteidigung | 18 | 7 | 90 | 0 | 0 | 0,21709631 | 0,208992918 | 0,0081
Verteidigung | 35 | 4 | 0 | 0 | 90 | 0,038329816 | 0,039952889 | -0,0016
Verteidigung | 30 | 11 | 90 | 0 | 0 | 0,105258496 | 0,098368671 | 0,0069
Verteidigung | 21 | 8 | 90 | 0 | 0 | 0,188018292 | 0,172844055 | 0,0152
Verteidigung | 35 | 12 | 0 | 0 | 90 | 0,013301646 | 0,013367138 | -0,0001
Verteidigung | 23 | 7 | 90 | 0 | 0 | 0,20173751 | 0,192310674 | 0,0094
Verteidigung | 20 | 6 | 90 | 0 | 0 | 0,240192045 | 0,232531357 | 0,0077
Verteidigung | 19 | 5 | 90 | 0 | 0 | 0,283017847 | 0,271962101 | 0,0111
Verteidigung | 18 | 5 | 54 | 0 | 0 | 0,171644946 | 0,165914856 | 0,0057
Verteidigung | 31 | 13 | 90 | 0 | 0 | 0,082095019 | 0,076394319 | 0,0057
Verteidigung | 19 | 4 | 90 | 0 | 0 | 0,341642954 | 0,31283088 | 0,0288
Torwart | 20 | 13 | 90 | 0 | 0 | 0,175279323 | 0,162450385 | 0,0128
Verteidigung | 31 | 11 | 0 | 0 | 90 | 0,016449758 | 0,016124265 | 0,0003
Verteidigung | 23 | 4 | 0 | 0 | 90 | 0,051344344 | 0,048781575 | 0,0026
Verteidigung | 38 | 11 | 59 | 0 | 0 | 0,056138179 | 0,056449646 | -0,0003
Verteidigung | 24 | 5 | 0 | 0 | 90 | 0,041714024 | 0,041708921 | 0,0000
Verteidigung | 29 | 10 | 0 | 0 | 90 | 0,019461571 | 0,018949149 | 0,0005
Verteidigung | 27 | 2 | 0 | 0 | 90 | 0,085014931 | 0,060388707 | 0,0246
Verteidigung | 21 | 3 | 0 | 0 | 90 | 0,067925732 | 0,058010729 | 0,0099
Verteidigung | 32 | 13 | 90 | 0 | 0 | 0,080273888 | 0,075133813 | 0,0051
Verteidigung | 26 | 6 | 0 | 0 | 90 | 0,034375683 | 0,035073286 | -0,0007
Verteidigung | 27 | 5 | 0 | 0 | 90 | 0,039085169 | 0,039678208 | -0,0006
Verteidigung | 22 | 4 | 0 | 0 | 90 | 0,052283349 | 0,049599975 | 0,0027
Verteidigung | 20 | 5 | 0 | 0 | 90 | 0,044699167 | 0,044579121 | 0,0001
Verteidigung | 18 | 7 | 90 | 0 | 0 | 0,21709631 | 0,208992918 | 0,0081
Verteidigung | 30 | 11 | 35 | 0 | 0 | 0,040933859 | 0,038254483 | 0,0027
Verteidigung | 38 | 11 | 0 | 0 | 90 | 0,013701522 | 0,014351605 | -0,0007
Verteidigung | 21 | 8 | 90 | 0 | 0 | 0,188018292 | 0,172844055 | 0,0152
Verteidigung | 35 | 12 | 0 | 0 | 90 | 0,013301646 | 0,013367138 | -0,0001
Torwart | 35 | 15 | 90 | 0 | 0 | 0,110415998 | 0,101844773 | 0,0086
Torwart | 20 | 13 | 90 | 0 | 0 | 0,175279323 | 0,162450385 | 0,0128
Torwart | 35 | 15 | 90 | 0 | 0 | 0,110415998 | 0,101844773 | 0,0086

comparison of the 2 formulas in recalc subskill 7 weeks run. Who could decide, which one is the better one.

**Comment by wsbrenk** [comment]
on average, the current formula makes 0.006 training points more per week than the proposed one

**Comment by wsbrenk** [comment]
> @wsbrenk sure there is no rush and happy birthday :-) !

thanks

**Comment by akasolace** [comment]
Fairly similar, I tend to believe there are much more backup on the other formula than in HO! one. 
At least I received many feedback on the forum telling me so .
