### ISSUE TITLE
Question about jar in HOHOME

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#35]
Hello,

On Linux, in the ho.sh , if the directory ~/.ho don't exist, we create it and copy jar from /usr/lib/ho/
After that we start the application from ~/.ho

When I install the new release, as the directory ~/.ho already exist it don't copy the new jar from /usr/lib/ho and I use the old revision.
Why we don't use jar from /usr/lib/ho ? If it's mandatory I think we must modify the script

PS: in the Splash screen I have 1.435 **DEV** (I don't know if it's normal)

**Comment by akasolace** [comment]
but in case of update, jars in  ~/.ho would be more recent than jars in /usr/lib/ho
so we would need to check if there are more reccent and copy only if it is the case

**Comment by yaute74** [comment]
Sorry but I don't understand.
How jar in ~/.ho could be more recent than jar in /usr/lib/ho ?
When we update the application it install the jar in /usr/lib/ho

**Comment by akasolace** [comment]
# Intro

1) until 1.434 included HO was hosted in `~/.hattrickorganizer`
2) new .deb creates data in `/usr/lib/ho/`

# .sh execution

#### step 1
```
if ~/.ho don't exist:
    copy data from /usr/lib/ho/ into ~/.ho
    if ~/.hattrickorganizer exists:
          copy db from ~/.hattrickorganizer into ~/.ho
```

#### step 2

```
if script launched from "/usr/bin":
     cd ~/.ho
else:
   stay in zip directory
```

# fresh install .db
        new files are installed in /usr/lib/ho/ 
       ~/.ho won't be updated because it already exists
       => this is not working
       the fix could be that the data copy from /usr/lib/ho/ into ~/.ho should be part of the post install script instead of ho.sh ?

# fresh install zip
         => should be ok

# update from .db
     new data are installed in ~/.ho   => should be ok

# update from zip
    new data are installed in folder => should be ok

**Comment by akasolace** [comment]
> 
> 
> Sorry but I don't understand.
> How jar in ~/.ho could be more recent than jar in /usr/lib/ho ?
> When we update the application it install the jar in /usr/lib/ho

No, when we update the app the jars and other files are installed in /usr/lib/ho if launched from usr/bin or installed in the unzipped folder, if launched from .sh within unzip folder

**Comment by akasolace** [comment]
I just realized my proposed solution would be fine for .deb and .rpm but maybe not for your arch packaging so maybe instead we can use one of the following alternatives.
1) instead of copying  from /usr/lib/ho/ into ~/.ho, we move the files 
2) we create a dummy .fresh file in the distribution. Then:
 files are copied from /usr/lib/ho/ into ~/.ho only is  .fresh exists. In that case .fresh is deleted
3) opposite approach: we leave the deb in the /usr/lib/ho/ folder and we don't cd to ~/.ho anymore, but in that case on fresh install the db is lost, so we need  a backup mechanism and to adjust the .sh

@yaute74 what do you think ?

**Comment by akasolace** [comment]
@yaute74 

> With this we separate data from package who never change (unless we install a new version) and are manage by the packager from user data who change and are not install with package.

this approach is more elegant but the problem is that at the moment there is no logic in HO code to handle /db folder and other ressources from different locations.  It is for sure doable but it will require important work I guess because code will have to hande Windows, OSX and Linux ressource path differently ! So, meanwhile, we can do something simple and maybe revert to my initial proposal:

> data are copied from /usr/lib/ho/ into ~/.ho as part of the post install script (first step of ho.sh wont be necessary anymore).

What do you think? I think I can do that for the .deb and .rpm (I have to try though as I am not 100% sure that is feasible), but, you do you think you can do that for Arch packaging? Otherwise no need to consider that option

> I am C developper but I practice java in the past. These days I didn't have time but I plan to help you for the development of HO. If you want I can study this solution, let me know...

There are clearly room in the project for an additional developer. And you know, I am not at all a professional developer and I haven't done any Java until 3 months ago when I wanted to make a patch for HO :-)

**Comment by yaute74** [comment]
@akasolace 
>  What do you think? I think I can do that for the .deb and .rpm (I have to try though as I am not 100% >sure that is feasible), but, you do you think you can do that for Arch packaging? Otherwise no need to >consider that option
Post intall script is not a problem for deb, rpm and archlinux
When we have a new release with a correction for #34 I create the package for archlinux
I will see how it work in HO for deb and rpm...

Question: you will create a branch for the 1.435 ? (for the maintenance and use the master for the future version)
how do you plan to work for version numbers ? In the 1.434 we have a another digit in the version number increase at each correction.

**Comment by yaute74** [comment]
ok great!

For info I do the modification for this issue, I just need to create a VM to test and after I send the pull request

**Comment by akasolace** [comment]
perfect, thank you !

**Comment by akasolace** [comment]
close by #46
