### ISSUE TITLE
No skills for sold players

### ISSUE THREAD

**Issue by orgogliobauscia** [akasolace/HO#45]
It often happens that sold players do not have the skills shown in the Sold players tab.
I found this but in 1.434 too.
<img width="1280" alt="screenshot 2018-12-15 16 09 14" src="https://user-images.githubusercontent.com/45899362/50044478-2fd9d980-0084-11e9-841c-bad96173746f.png">

**Comment by akasolace** [comment]
I guess that it depends if old players was kept or not in the database

**Comment by orgogliobauscia** [comment]
Jameson's skills were downloaded while he was in my team (for 3 days), and were visible. When he was sold and I pressed the "Ricalcola trasferimenti" button the skills were no more visible.
Hoffmann's skills were visible in the transfer list part of HO. When he was fired from the team who bought him the skills were no more visible.

**Comment by brokenelevator** [comment]
the database does not get rid of players. At least I don't think it does. This is one of the issues that I saw (and heard of) long time ago. I will look into it when I have time.

**Comment by orgogliobauscia** [comment]
Thanks.

**Comment by akasolace** [comment]
@mistermax80  @brokenelevator 
this will be the last open issue for 1.436, hence I also assigned to mistermax in case he can help.
I haven't looked at it at all. I don't know how problematic it is an how difficut it is to fix it.
Let me know if you think you can fix it before 1.436 (we can make a beta for the end of this week if no new bugs are coming in) , if it is too much work, we may postponed it for 2.0. 
Cheers

**Comment by brokenelevator** [comment]
@akasolace @mistermax80 I see a lot has changed over the last 24ish hours. So I guess I should update on this issue. In my fork there is a branch issue45. Player's transfer history is no longer removed for fired players(on update player button). I could PR it but there is more to it than that. It is more of a time matter rather then difficulty. I know how to fix rebuilding transfer history(the other button) so that it doesn't remove history on fired players. I will do it asap but I have deadline to match right now. I also thought to add an information that player was fired (using existing language string) in the panel just above the history list. I have a rough idea how to do that. Lastly, I have yet to find out why the data is missing from the top panel. But that is likely also just a matter of time.

**Comment by akasolace** [comment]
@brokenelevator 
ok thank you for the update. I see you are on top of that issue so I will leave it with you.
Eventually the beta will be published after the holiday period so it removes the time constraints.
Keep us posted.
Cheers

**Comment by akasolace** [comment]
@mistermax80 
I was not sure brokenelevator was looking at it but based on previous message, he remains the lead on that issue.

**Comment by brokenelevator** [comment]
@akasolace No problem. I'll keep the branch updated and maybe check back here. If not just notify me somewhere.

**Comment by orgogliobauscia** [comment]
Many thanks for your replies on the matter.
If you need a tester for the sold players problem, please let me know.

**Comment by brokenelevator** [comment]
**Update**: rebuilding transfer history now correctly parses fired players (as long as they are in the database)

_more to come :)_

**Comment by akasolace** [comment]
@brokenelevator well done !

> more to come :)     

the teasing makes me curious... looking forward to seeing the PR :-)

**Comment by orgogliobauscia** [comment]
> **Update**: rebuilding transfer history now correctly parses fired players (as long as they are in the database)

When will this version be available?
Thanks :-)

**Comment by brokenelevator** [comment]
@orgogliobauscia Well, this is technically already ready. Also, player data is no longer missing from transfer history top panel. Additionally I refined recognition of fired players on team transfer update.
So, the main thing is done. I plan to add fired player notification and remove transfer button. There are also minimal layout fixes and possibly extending team transfer update to also include individual histories.

The problem with DEV release would be @akasolace being away on holiday and since he runs this I don't want to make a mess. I most likely can produce DEV build but wouldn't feel comfortable making it official. It is your call.

**Comment by akasolace** [comment]
@orgogliobauscia @brokenelevator 
Hello I will be back from holliday end of this week. I will try to make a new DEV build on Sunday.

**Comment by orgogliobauscia** [comment]
I am looking forward to testing it.
Thanks, enjoy your holiday.

**Comment by brokenelevator** [comment]
@akasolace All done(#67).  Ready to be put in DEV release. I skipped release notes so to not conflict with the other PR(#64).

**Comment by akasolace** [comment]
closed by #67

**Comment by orgogliobauscia** [comment]
Just to let you know that the HO_1.436.0.363_OSX.zip version works perfectly.
I've got back skills of players I had completely forgotten :-)
One thing: the HO icon is no more the usual one.
Many thanks for your support.

**Comment by akasolace** [comment]
> One thing: the HO icon is no more the usual one
could you please provide more info ...

**Comment by mistermax80** [comment]
@akasolace I Tried, the icon on mac is missing... I think that refer @orgogliobauscia

**Comment by orgogliobauscia** [comment]
> > One thing: the HO icon is no more the usual one
> > could you please provide more info ...

[https://snag.gy/fcg5QH.jpg](url)

**Comment by akasolace** [comment]
@mistermax80   @orgogliobauscia indeed a bug report is needed
thank you

**Comment by mistermax80** [comment]
@orgogliobauscia  Let me know If you open that bug.
Thanks so much.

**Comment by orgogliobauscia** [comment]
> @orgogliobauscia Let me know If you open that bug.

I'll do this immediately.

**Comment by akasolace** [comment]
@orgogliobauscia   thank you

**Comment by brokenelevator** [comment]
@orgogliobauscia Glad it works for you :)
