### ISSUE TITLE
Sub-level recalculation error

### ISSUE THREAD

**Issue by fjrn** [akasolace/HO#512]
When requesting HO to Recalculate sublevels or Recalculate sublevels (7 weeks), the following error occurs:
java.lang.NullPointerException
![java lang NullPointerException](https://user-images.githubusercontent.com/64761641/81481744-92e38780-9208-11ea-8880-9360d4184cb9.JPG)

**Additional information**
![Error](https://user-images.githubusercontent.com/64761641/81481571-89a5eb00-9207-11ea-950e-d8ee8509541b.JPG)

**Comment by fjrn** [comment]
Obrigado pela atenção. Se precisar de mais informações, eu estou a disposição.

**Comment by akasolace** [comment]
@fjrn  a copy of your db would help looking at this issue ... thank you

**Comment by fjrn** [comment]
[db.zip](https://github.com/akasolace/HO/files/4617841/db.zip)

**Comment by wsbrenk** [comment]
db contains only one single training. subskill recalculation seems to skip the very first training.

with current master i could not reproduce the npe

**Comment by akasolace** [comment]
@wsbrenk just to clarify is it that we can't reproduce the error or that the error only occur if user tries to recalculate subskill when there is only one training in the database ?

**Comment by wsbrenk** [comment]
@akasolace i could not reproduce the npe given by @fjrn. i think we still did repare it the last weeks. wasn't there another ticket concerning "getAufstellung"?!

what i saw, was that there is still another bug which happens if only one single training is in the database and all stored hrfs are after the trainings date. Then NO recalculation is done.

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/83980902-8e9aaf00-a919-11ea-93be-a7fa900c8a6f.png)

recalculation is done now also on trainings that took place before the first hrf was loaded.

i did introduce a lazy loading option to HOModel, since a lot of stuff was loaded by HOVerwaltung.loadModel which is not needed by the recalculation method.

**Comment by fjrn** [comment]
Thank you for your service.
I can't interpret the error report, so I can't comment on the error. I believe that the proposed improvement will increase the yield.
The sub-level recalculation is working perfectly
