### ISSUE TITLE
[FEATURE]Enable automatic upgrade from HO! 3.0 to HO! 4.0

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#599]
i read the doc "How to upgrade from HO! 3.0 to HO! 4.0" and would like to have an automatic upgrade process. I took a quick look at the refactoring of the user class - good job.
if the change from xml to json is the only reason for the manual upgrade steps then i want to make the suggestion to read the base user infos from the existing xml file if the json is not yet in place. This could either be done in the catch block of the json read method or once in the Dbupdate step when upgrading to DBVersion 400 is done.

**Comment by wsbrenk** [comment]
btw: shouldn't we mention the gson library in the dependencies chapter of https://github.com/akasolace/HO ?

**Comment by akasolace** [comment]
>if the change from xml to json is the only reason for the manual upgrade steps then i want to make the suggestion to read the base user infos from the existing xml file if the json is not yet in place. This could either be done in the catch block of the json read method or once in the Dbupdate step when upgrading to DBVersion 400 is done.


It will not be the only difficulty:
    -  the location of the db is also modified
    -  the installation folder is modified
    -  plus lot of changes made via the post install script

I really don't see how to make automatic upgrade from 3.0 to 4.0.

What can be done, might be a database importer. I mean user do fresh install of 4.0 and then we create an entry like `File -> Import DB`  The user would select its xml, and the rest might be done automatically. This is feasible but that would be still some work though.

**Comment by akasolace** [comment]
> btw: shouldn't we mention the gson library in the dependencies chapter of https://github.com/akasolace/HO ?

Yes good point I think we can do that ...

**Comment by akasolace** [comment]
@wsbrenk @tychobrailleur @DavidatorusF @yaute74  is it something we want to offer or do we leave it up to the user to do it manually ?    if we create this functionality I think it should be integrated with #558 (repair db),  something like:
    - 1) file | repair db -> repair the db
    - 2 ) file | import -> read the user.xml or user.json and put the db in thre right place
    - 3) file import + report db -> import + repair db does 1) +2)

**Comment by wsbrenk** [comment]
@akasolace what do you think about a dialog box when database is initialized which asks for the destination of an old user.xml or user.json?

**Comment by akasolace** [comment]
>  @akasolace what do you think about a dialog box/fileselection when database is initialized which asks for the destination of an old user.xml or user.json?

I updated my comment above to take this in consideration

**Comment by akasolace** [comment]
@tychobrailleur  what do you think of https://github.com/akasolace/HO/issues/599#issuecomment-658713633 ?
I think this would close both #588 and #599 ...

**Comment by tychobrailleur** [comment]
> @tychobrailleur what do you think of [#599 (comment)](https://github.com/akasolace/HO/issues/599#issuecomment-658713633) ?

I haven't looked into integrating the DB repair tool to HO, especially given I had come to the conclusion that this should remain a standalone tool (in a comment which I cannot retrieve because I can't figure out how to search for them...).  One challenge I see for example is that the app very likely would not even start in the case of a db corruption.  But something I can investigate if you feel this belongs into HO.  In any case, it'd be good to have another set of eyes on the code: https://github.com/tychobrailleur/hodb-repair

However, I must admit I don't quite see how the DB repair tool fits into the 4.0 upgrade discussion.  I have mentioned it a few times before, it doesn't do any version migration at all: it simply attempts to retrieve data from an existing db as much as possible, and reimport into a target schema (3.0, 4.0, or [identical](https://github.com/akasolace/HO/issues/597#issuecomment-662018527)).  If for some reason the source schema is incompatible with the target schema, it will fail.  

If we want to have an automated path to 4.0, we must have an explicit logic to:
- Detect that we are starting a 4.0 app on a 3.0 config,
- Load existing config, and convert to 4.0 location and format,
- Run database migrations (on 3.0), and save into 4.0 location at exit,
- Optionally delete 3.0 artefacts.

**Comment by akasolace** [comment]
@tychobrailleur Just to clarify what I had in mind.  I imagined some new entries in file/db: 
     - an entry called db repair, how would have let the user call dbRepair tool on his corrupted database. Something like close HO and launch the tool with the rights command line options... It would have maybe in some case allow the user to recover a corrupted database. Something the user could do directly withtout opening a ticket on github but maybe this make little sense. I was just throwing an idea really.
      - another entry was import database. I do not want to support upgrade from 3.0 to 4.0 This would be too much work. We will only offer fresh install for 4.0 so existing user would need to do the following: 
     - single team user, launch HO 4.0 and replace the db folder with the one from its current 3.0 install
      - multiple team users, launch HO and manually edit the newly created users.json file. 
Hence, as suggested by @wsbrenk we could simplify the transition, by offering import of a previous database. HO would read users.xml and would create users.json and databases folder accordingly. I think much of the user have a single team so maybe it is too much work for too few users. Maybe a clear documentation on how to upgrade from 3.0 to 4.0 is sufficient. In that case I would close this issue and replace it with a ticket "improve documentation for upgrade from 3.0 to 4.0" Considering the number of remaining tickets for 4.0 I am happy to go for the simple approach. @wsbrenk @tychobrailleur  what do you think ?

**Comment by akasolace** [comment]
replaced by #672
