### ISSUE TITLE
[FEATURE] support of man-marking order

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#660]
![manmarkingOrder](https://user-images.githubusercontent.com/11821502/89227524-221cf300-d5de-11ea-94a9-4fad0a7993ca.png)

Currently teamanalyzers team view is my favorite. a 4th button in SubstitutionOverview could start the team analyzer and some drag+drop action could create the man marking match order. But i don't have any idea how to implement that - up to now.

would be great if you could help me.

_Originally posted by @wsbrenk in https://github.com/akasolace/HO/issues/632#issuecomment-668243486_

**Comment by akasolace** [comment]
@wsbrenk I haven't followed everything regarding man marking order and it is a functionality I only used once or twice in game. 
However, do we really need a new GUI for this? can't we not simply list the players in opponent team like what HT is doing? Relying on last position might be misleading, no?

**Comment by wsbrenk** [comment]
@akasolace it is not as easy as it looks like. in lineup panel, there is no access to opponents information until now. the idea is to use the existing team analyzer view. Editing the lineup (man marking order in substitution view) has to set lineup information in teamanalyzer and the rest of the man marking editing has to happen in team analyzer.

**Comment by akasolace** [comment]
@wsbrenk it sounds very complicated and I would have clearly taken a much simplified approach: I would have done it all in the order tabs, a new man marking order along substitution and replacement .... simply with a dropdown listing opponent players. 

> in lineup panel, there is no access to opponents information

I think there are 2 ways to deal with it:

 1. at data download we fetch list of players for upcoming opponenent and that information is stored in a hashmap like 5 teamIDs and 5 list of strings
 2. in lineup tab we add a field for opponent : 
   - if selected info are populated accordingly (home/away, TS, .....)
   - have possibility to put 'sandbox' to keep existing behaviour (which is lineup simulator in HT)


For sure, I would not have done any GUI .... but it is up to you :-)

**Comment by wsbrenk** [comment]
@akasolace up to now i really don't know what's the heavier way. as far as i understand you right, we have to double all or nearly all the download stuff that is already done by the team analyzer. the gui part proposed by you is easier to implement, that's right.

**Comment by akasolace** [comment]
> as far as i understand you right, we have to double all or nearly all the download stuff that is already done by the team analyzer

I might be wrong but I think it is quite straightforward: we can reuse the parser of players.xml but we will just need to store the list of opponent player last names (similar to HT).

**Comment by akasolace** [comment]
Also more generally, we can't make assumption that the user will want to mark a player that was aligned in last lineup, I think it is more robust just to list them all.

**Comment by wsbrenk** [comment]
@akasolace before you can download opponents player, you have to download and select the upcoming opponent teams. as we talked about man marking the very first time, half a year ago, i suggested to integrate the team analyzer to the lineup panel.

**Comment by wsbrenk** [comment]
> Also more generally, we can't make assumption that the user will want to mark a player that was aligned in last lineup, I think it is more robust just to list them all.

that'S of course correct. in team analyzer the user not only can investigate the last lineup of the opponent but all he selected to download. he very easily could see which player sits on the same position each match or if there is a pattern how the positions are swapped.

if there are new players in the team - fresh from the market/transfer list, those players are missed by the team analyzer approach.

**Comment by wsbrenk** [comment]
since i'm not the gui expert i asked @tychobrailleur if he wants to take over this issue, at least the gui part of it.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/90984423-21400700-e575-11ea-8c00-ac2818a3faf0.png)

after one day of learning JComponent's positions and their parents positions i've got this. it is not nice and does still not work as expected (every time). my last commit is mentioned above.

**Comment by tychobrailleur** [comment]
I have spent quite a while trying to do something similar with `JLayeredPane` but haven't made much progress – for some reason I keep getting errors.  

I'll try a bit more, but I am still not convinced this approach is the way to go for this feature.  I was more envisioning:
- Either a simple list of all the players of the selected opposing team,
- Or porting the view above (match list + position on pitch) to a panel in the `Match Orders` tab, where you simply click on “marker” and “marked”, and set those players with a specific colours for each.

Which makes me think: rather than an arrow, maybe simply add a specific colour for each on the view above would be sufficient?  I still think however being brought to the Matches tab for this would be confusing?

**Comment by wsbrenk** [comment]
lineups and opponent analysis fit together wonderfully in my opinion. my suggestion would be to pack them together - not to double their features, no new match panel or things like this.
i'm not happy with the idea, drawing a line to edit/display a man marking order. i thought kloppo would have used chalk lines twenty years ago to convey his ideas to his defender.

**Comment by akasolace** [comment]
As I said before I think we should go for something really simply: a combo box like in HT. A complex GUI interface, as the one proposed, will not bring much in my opinion and will be error-prone and difficult to maintain. I think the support of man-marking is a great addition, let's make it simple and deliver it with 4.0. 
@wsbrenk how much work would that be to have it finalized with a simple combobox? Maybe you can have this done for 4.0 and we have another ticket specifying "GUI interface for man-marking order" or "merging lineup and opponent analysis". We would mark those tickets with a long dated milestone and we will have time to discuss what we want to do and GUI mockup before implementing. How does that sound ?

**Comment by wsbrenk** [comment]
@akasolace good idea - i will continue with a simple combo box first.

**Comment by akasolace** [comment]
> @akasolace good idea - i will continue with a simple combo box first.

great, I really think this is the right approach

**Comment by akasolace** [comment]
@wsbrenk for my info, do you have the icon you want to use for man marking order ? Otherwise you can list your need in #674 ...

**Comment by wsbrenk** [comment]
@akasolace i found a svg file, but i do not know how to use it. the other icons in order overview are png file icons.

**Comment by akasolace** [comment]
That is perfect if you already have a svg because as you know we are in the process to convert all png to svg. @tychobrailleur already made lots of commits to convert from png to svg, have you look at code sample?  

>  the other icons in order overview are png file icons.

Everytime you encounter a png file still in use in HO, do not hesitate to list it in #674, this ticket will be a tracker for svg icon request.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/91843558-3cd29e00-ec56-11ea-8e79-b693f593cc9e.png)


progress report: 
this is the man marking edit dialog.
the opponent team is selected by team analyzer

**Comment by akasolace** [comment]
@wsbrenk I really like the combobox !!

- the position is the last played position?  can you get this one directly from players.xml or do you have to parse a lot of files ? 
- you put age and experience, I don't think it impacts really the man marking effectiveness.  I think what could be more useful, is indication of the specialty (green (Tech) and red (Unpred) similar color than for weather penalties/bonus) and maybe either a hoover message or a text somewhere giving info  (-10% all skills, boost of 8% because technical, ......)

**Comment by akasolace** [comment]
@wsbrenk I see you submitted your PR already so maybe the follow could be an open ticket for discussion for 5.0

> the position is the last played position? can you get this one directly from players.xml or do you have to parse a lot of files ?
you put age and experience, I don't think it impacts really the man marking effectiveness. I think what could be more useful, is indication of the specialty (green (Tech) and red (Unpred) similar color than for weather penalties/bonus) and maybe either a hoover message or a text somewhere giving info (-10% all skills, boost of 8% because technical, ......)

**Comment by wsbrenk** [comment]
> * the position is the last played position?  can you get this one directly from players.xml or do you have to parse a lot of files ?

it is from players.xml

**Comment by wsbrenk** [comment]
> * you put age and experience, I don't think it impacts really the man marking effectiveness.  I think what could be more useful, is indication of the specialty (green (Tech) and red (Unpred) similar color than for weather penalties/bonus) and maybe either a hoover message or a text somewhere giving info  (-10% all skills, boost of 8% because technical, ......)

i put a lot of stuff into this line which is not viewable at all. i would like a discussion of what information should be displayed in this line and how.

**Comment by wsbrenk** [comment]
the approach of displaying as arrow in team analyzer is still in place and i would like to go on with that the next time.

**Comment by akasolace** [comment]
> i put a lot of stuff into this line which is not viewable at all. i would like a discussion of what information should be displayed in this line and how.

ok do you want me to review/merge your PR already or do you want to discuss this first ?

**Comment by wsbrenk** [comment]
i'm a friend of proposal number 1)

there are a lot of things, that can be done further on concerning the man marking.

**Comment by akasolace** [comment]
closed by #680
