### ISSUE TITLE
[FEATURE] influence of man marking order on ratings

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#661]
Calculate the influence of the order on ratings

user should be able to
- simulate the effect of own man marking orders
  - in case his assumption is correct
  - in case the opponent does not fulfill this assumption
- simulate the effect of opponent man marking orders
  - same cases as above

**Comment by akasolace** [comment]
this might be a tricky one to implement, I put it on the backlog to keep track of it ....

**Comment by wsbrenk** [comment]
@akasolace absolute confirmative

**Comment by wsbrenk** [comment]
[https://www85.hattrick.org/Forum/Read.aspx?t=17308544&n=14&v=0](url)

**Comment by wsbrenk** [comment]
[info in unwritten manual](https://www85.hattrick.org/Forum/Read.aspx?t=17308544&n=14&v=0)

**Comment by masterpatje** [comment]
I am unsure if this comment is valuable, but I noticed that man marker influence tactic skill. Centre attack or wing attack and even counter attack are influenced. This dus to the fact that for example passing is also reduced by the penalty involved by the man marker formula.

**Comment by masterpatje** [comment]
And the man marker formula is known. Maybe as an extra in the miscellaneous tab you can include the formula and then select a certain player from your team and manual select the highest skill from the oponent to see what the resulting skill will be for your own player. For example if player A (your team) has a 15 skill on defending and 12 on postional midfield and 10 on passing and player B (manually set to highest skill 15) the result will be player A after penalty 7,5 DEF, 6 PM en 5 passing.

**Comment by masterpatje** [comment]
Lastly it might be nice to indicate with an indicator on which positions you can play man marker and penalties considered.

For example when equal DEF skill vs head skill opponent;
DEF vs FWD = 50% penalty for own player
DEF vs IM = 65% penalty for own player

These examples are clear, but targeting wingers was/is a bit more unclear. You can target them with WB and maybe with IM's but not with WB if I am correct.

So understanding Man Marker with HO could be a nice feature. But maybe not for now. Now you have to look at the internet because hattrick manual is also very limited in explanation...

**Comment by wsbrenk** [comment]
same as #682, #1387
