### ISSUE TITLE
[BUG] column positions and width of player overview are not saved anymore

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#677]
every time i start HO, the colums are on their initial positions. all changes i did are resetted.

version: dev on master branch

**Comment by akasolace** [comment]
this is intentional, change was made by @tychobrailleur in DBUpdater  (cf https://github.com/akasolace/HO/blob/76bf35dd060fc87a0fc0ac9dca27766e43d7a85a/src/main/java/core/db/DBUpdater.java#L119)
This was following upgrade to darklaf.  User will experience it just once, when they uprade.

If that is ok with you can close this issue ....

**Comment by wsbrenk** [comment]
@akasolace i see - yes you can close it.
