### ISSUE TITLE
sanitise ressource files both in jar and external folder

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#71]
some ressources might not been in use on some (or maybe all ) platform. Ideally we should remove them when not necessary / not in useed: it will be cleaner and less misleading.
I invite you to test is and report your findings in the table below using the DEV binaries:

| Required  Y/N ? | spraches / translation folders | flags | prediction | themes |
|---------------------------------|--------------------------------|-------|------------|--------|
| Windows (installed application) |N|N |Y |Y |
| Windows (zip) |N|N|Y| Y|
| Linux(installed application) |N  |N  | ? | ? |
| Linux (zip) | N | N | ? | ? |
| MacOS | N/A |N/A  |N/A  |N/A  |

**Comment by akasolace** [comment]
ok so I started to fill the table

**Comment by DavidatorusF** [comment]
no need sprache and flags on ubuntu 16.04

**Comment by akasolace** [comment]
ok then I will remove sprache and flags folders from: zip, .exe, .deb and .rpm

**Comment by brokenelevator** [comment]
@akasolace I'd say all the resources are actually used, somewhere. The reason those appear not used is that you purposely or not changed the jar file contents and made the name uppercase (irrelevant for the issue).

Original jar contained:
`de` with some two classes
'gui' with as name would suggest some gui imagery (smilies, arrows and so on)
'ho' with HO class files
`META-INF` with manifest file
`HOLauncher.class` self explainatory
'revision.num' used by the splash screen and top bar (maybe more)

New jar contains:
`core` with HO class files. previously in ho, makes sense since you changed all package names to remove the prepending `ho`.
`flags` with flags. previously in the main folder, outside jar. so the one still residing outside jar file is not used.
`gui` as before
`META-INF` as before
`module` as with core
`prediction` as with flags
`sprache` also as with flags
`tool` as with core
`changelog.txt` which is now both in jar file and outside it
`HOLauncher.class` as before
`ho_logo.png` self explainatory
`hsqldb_lic.txt` that should be in docs. possibly outside jar file.
`LICENSE.TXT` self explainatory. don't know if it's the best place for the file
`logo.ico` self explainatory, now both in jar file and outside it
`README.Feedback.txt` as if anyone will look in jar file
`release_notes.txt` as above

My approach is simple. Data don't fall of the tree. If there are language strings (or flags or whatnot) used, they must come from somewhere. So when I read `sprache is not used` I was like `what?`.
Now it needs to be sorted which ones are wired, or just rewiring things to how they should be.

**Comment by akasolace** [comment]
@brokenelevator 
When we removed the depracted ``update translations`` and ``update flags`` features I willingly include those data within the jar. But at that time I forgot to remove the external folder. When I said to Davidatorus that he can't change translation locally I meant regular users can't do it. Obviously a developer still can do it by editing files within the jar.
For prediction, I also removed the update functionality, however, I asked around (HT forum) and was told lot of users are using tweak version of prediction files. Hence folder has to remain external. Ideally it should be moved out of the jar. 
Regarding all other files, changelog, licence, ect.. they clearly should also be removed. 
Regarding /theme it is the opposite it should be within jar and not in external folder (I wanted to remove that but I users are still using some of those themes).

So I agree there is plenty of cleaning to be done. I will do that tonight.

**Comment by mistermax80** [comment]
on Macos, in user folder I see the following folder:
- Lineups (used)
- logs (used)
- themes (I tried to remove and after restart the folder has been recreated) folder empty
file users.xml
The content reported in HO.app, is:
![schermata 2019-01-10 alle 17 10 24](https://user-images.githubusercontent.com/15519907/50981185-b60a0400-14fa-11e9-9245-f89e1cd43895.png)

I hope I have been to help you... else, let me know how I must check.

**Comment by brokenelevator** [comment]
@akasolace I do get what you mean by regular user but @DavidatorusF isn't necessarily one. Still you don't have to be developer to edit jar file. Obviously most wouldn't but...
As for `themes` you mean custom (or customized) ones? Why else wouldn't we just put them in jar?

**Comment by akasolace** [comment]
@brokenelevator  regarding themes. My first idea was simply to remove those 2 themes because I thought no one would use them until Davidatorus told me differently.
I agree this folder should be within the jar.

**Comment by DavidatorusF** [comment]
@DavidatorusF in fact when werder implemented this new theme I'd tested it for him..
may be I'm the onlyone who use it ^^

**Comment by akasolace** [comment]
lot of icons are missing in that theme !
