### ISSUE TITLE
[BUG] Error when trying to download new data

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#786]
**Describe the bug**

Since yesterday, trying to download new data raise:

![image](https://user-images.githubusercontent.com/1136496/99500298-7031e880-297a-11eb-952a-65eb7fb5b513.png)

Some data are downloaded but not everything.

@wsbrenk are you experiencing it ?

**Comment by johari75** [comment]
I face that problem since beginning of this week.
Downloading matches does not work any more.
In the League Details tab I can see that my last match is downloaded but in the Matches tab there are no data about it.

Additionally the list of opponents in the TeamAnalyzer tab decreases by the last opponent (it is the only one I had both matches of this season)

**Comment by tychobrailleur** [comment]
Same here

**Comment by johari75** [comment]
It works again. CHPP problems?

**Comment by tychobrailleur** [comment]
> It works again. CHPP problems?

Yes, it must be, although right now it is looking ok. (also works for me again)

![Screenshot from 2020-11-18 08-24-36](https://user-images.githubusercontent.com/114285/99504491-838f8480-2977-11eb-837a-3c7056504035.png)

**Comment by johari75** [comment]
I checked the status yesterday. It looked like this too but didn´t work.

**Comment by akasolace** [comment]
looks like things are back to normal. It should have been a non reported issue on CHPP side.
