### ISSUE TITLE
[eFEAT] move Update feature from File menu to Help menu

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#82]
In order to be consistent with other softwares:

``Update HO!`` -> ``Check for updates...``
``File`` -> ``Help``

**Comment by yaute74** [comment]
Modification done:
- move check update to help menu
- add release note entry in help menu

**Comment by brokenelevator** [comment]
@yaute74 I don't know why are you so keen on using links and opening browser. I, for one, am not. I would open a dialog, just like when checking updates. Just a thought.
What do you think about that @akasolace?

**Comment by yaute74** [comment]
@brokenelevator I am not 'so keen' it's just a solution as dialog is an other solution. I find it's more cleaner, less code, less bugs. On computers, in most cases a browser is already open.

**Comment by akasolace** [comment]
@yaute74   I just tried and it is not working as expecting, does not find update wheras:

https://akasolace.github.io/HO/latest.html   shows  version=1.436.0.795 released=15.01.2019


![image](https://user-images.githubusercontent.com/1136496/51207067-138ebe00-190a-11e9-8eb6-80ae95647fa8.png)

**Comment by akasolace** [comment]
closed by 9b0fb68fe2e60c7ac912bc2d02f5f88842c9bf00

**Comment by brokenelevator** [comment]
@yaute74 true, solution is a solution. one that I don't like, but that is fine. I don't find that particularly cleaner but sure, less code, less bugs.
I never liked that behavior. Meaning applications opening browser. For that reason I don't change default browser setting and copy, rather than click links. If links do open, I can just kill it or black hole it, leaving my browser not run or not bothered.
