### ISSUE TITLE
[BUG] Button "Help improve rating prediction" doesn't work in other time zones

### ISSUE THREAD

**Issue by velikodsky** [akasolace/HO#837]
**Describe the bug**
When pressing the button "Help improve rating prediction" in Lineup, the message is showed "Your data is not recent, last update is 31 груд. 2020 р. 12:11:59, please start by downloading new data from Hattrick". But I just downloaded the data. It is 31.12.2020 13:12 UTC+2 now.

The problem is in the time zone difference: Hattrick time is 12:12, but my local time is 13:12. When I change time zone to Stockholm, the button works normally.

**Platform information:**
 - OS: Arch Linux
 - Version HO-4.1.3310.2-portable-unix

**Comment by akasolace** [comment]
ok thank you.
At the moment unfortunatly this feature is not functioning.

**Comment by akasolace** [comment]
An immediate solution is anyway to disable the button rating prediction.
However, this should be fixed because it might impact other area where the same code logic is applied. 
@velikodsky could you please test latest dev version (5.0) and see if you have same kind of error on the lineup tab? A refresh of data is requested before allowing setting up lineup. I guess in your case you might experience similar issue....
TODOs:
 - [ ] 1.0 disable rating prediction button until further notice ...
 - [ ] 2.0 fix code logic detecting last data refresh to account for different time zone ...

**Comment by akasolace** [comment]
@velikodsky could you please test latest dev version (5.0) and see if you have same kind of error on the lineup tab? A refresh of data is requested before allowing setting up lineup. I guess in your case you might experience similar issue....
