### ISSUE TITLE
[BUG] Provide 32 bits installer

### ISSUE THREAD

**Issue by gescobita** [akasolace/HO#928]
**Describe the bug**
Hi, when I try to install the last version of HO, it send me this messagee
"The version of this file is not compatible with the version of windows you're running. Check your computer's system information to see whether you need an x86 or x64 version of the program."

I have tried to install both with JRE and without and am getting the same error message.

**Platform information:**
 - OS: [Windows ]
 - Version 7 service pack 1
 32bits

Thank you

**Comment by akasolace** [comment]
@gescobita  I will shortly release some 32bits artefacts (next week ? ) , I will et you try and provide feedback...

cheers

should be closed by 119f620f85e57a491c0cbfe1bfc55894a16b027e

**Comment by akasolace** [comment]
@gescobita could you please try the 32 bits installers ?

**Comment by gescobita** [comment]
Hi, I've tried with (HOSetup-32bits-5.0.3436.0-DEV-JRE.exe) and gives me the same error that in the original post.

After I tried with (HOSetup-32bits-5.0.3436.0-DEV.exe) and it shows me this ""The install4j wizard could not find a Java(TM) Runtime Environment on your system"


I downloaded the Zip files, but I don't know how to use them, and I failed to understand the info on Documentation. sorry :(

Also sorry for my English, I'm not a native speaker and thank you very much for your patience.

**Comment by akasolace** [comment]
@gescobita try to install the JRE (https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jre_x86-32_windows_hotspot_15.0.2_7.msi)
and try again to use the version HOSetup-32bits-5.0.3436.0-DEV.exe, let me know how it goes ... 
thank you

**Comment by akasolace** [comment]
@gescobita there was a bug with HOSetup-32bits-5.0.3436.0-DEV-JRE.exe that I just fixed ( I think). 
In case you can't install the JRE on your PC please wait until I produce new artefacts with JRE included. 

> I downloaded the Zip files, but I don't know how to use them

If you download a zip including JRE you just need to launch the program HO.exe, if you downloaded a zip without JRE you need to install if by yourself (see link in post above) and then you can just launch the program HO.exe.

Usually portable app are best for testing (which is the case for this version) or if you don't have right to install HO! on your PC otherwise you should go with the normal setup.  

Similarly if you can install JRE on your PC it is best to do so (you will have better performance) if not you should use a version of HO! bundling a JRE.  Let me know if you need more help.

**Comment by gescobita** [comment]
I installed JRE and after that installed HO!, I opened it and started to use it, I got the CHPP code and download my team info, after that I closed it and when I opened it again it show me the next message:
![imagen_2021-03-04_110158](https://user-images.githubusercontent.com/79470364/110000545-09da9700-7cd9-11eb-9daf-4fa7e359d758.png)

I uninstalled and reinstalled, but the message stills shows. Thank you.

**Comment by akasolace** [comment]
@gescobita I will try to reproduce

**Comment by akasolace** [comment]
@gescobita if I understand correctly, you made a fresh install of HO!. Then you managed to do your first download. However after closing HO! and reopening it (2nd time) you got the error message above, right ?
